### ISSUE TITLE
No Response From Web Server

### ISSUE THREAD

**Issue by skyballengine** [AbdulelahHamoud20/Calculator-Microservice#1]
Based on what I'm seeing, it doesn't look like the web server is receiving the request at the moment. I used a print statement on the second line of the calculate function to check if it was called, and nothing printed.

**Comment by AbdulelahHamoud20** [comment]
I will reach out to you on slack to look further into the issue, thanks

**Comment by skyballengine** [comment]
Hey Abdulelah, I was having a hard time getting requests to come through and give responses, so I made a few changes that helped me get there. It was probably a lack of understanding on my part, but I just switched a few things to make it work in a way that I understood. 

I'm going to submit a pull request, not because you should accept my changes, but mostly just because I've never done it before, feel free to check the changes out and see if you'd like to merge, if not, that's totally fine too. I just want the experience. 

Cheers,
Sky
